[package]
name = "lilyutils"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "fmt", "chrono"] }
